version: "3.8"
services:
    getprint_service_user:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: getprint_service_user
        ports:
            - 8888:8888
        environment:
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=getprint_users
            - DB_PORT=3306
            - PORT=8888
networks:
    default:
        external:
            name: mysql_default
