version: "3.8"
services:
    getprint_service_user:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: getprint_service_user
        ports:
            - 8000:8000
        depends_on:
            - getprint_service_user_mysql
        volumes:
            - .:/app
        working_dir: /app
    getprint_service_user_mysql:
        image: mysql:5.7
        container_name: getprint_service_user_mysql
        command: mysqld --user=root
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=getprint_users
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=root
